services:
    as3_modlr.data_types.factory:
        class: As3\Modlr\DataTypes\TypeFactory

    as3_modlr.event_dispatcher:
        class: As3\Modlr\Events\EventDispatcher
        public: false

    as3_modlr.storage_manager:
        class: As3\Modlr\StorageLayerManager
        public: false

    as3_modlr.store:
        class: As3\Modlr\Store\Store
        arguments:
            - @as3_modlr.metadata.factory
            - @as3_modlr.storage_manager
            - @as3_modlr.data_types.factory
            - @as3_modlr.event_dispatcher

    as3_modlr.util.entity:
        class: As3\Modlr\Util\EntityUtility
        arguments: [ @as3_modlr.rest.configuration, @as3_modlr.data_types.factory ]

    as3_modlr.util.validator:
        class: As3\Modlr\Util\Validator
